dist: trusty

language: node_js
node_js:
  - '10'

cache: npm

env:
  - CI_ENV=travis

install:
  - npm install

jobs:
  include:
    - stage: lint & test
      script:
        - commitlint-travis
        - npm run lint
        - npm test
    - stage: deploy docs
      if: branch = master
      script: ./deploy.sh
