dist: trusty

language: node_js
node_js:
  - '10'

cache:
  npm: true
  directories:
    - node_modules # NPM packages

env:
  - CI_ENV=travis

install:
  - npm install

script:
  - commitlint-travis
  - npm run lint
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
